#
# Global site config
#

# [site encoding]
encoding: utf-8

# [Name of visual theme]
#theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0

# [The title of your site]
title: My Git Utils

# [A short description of your site's purpose]
description: The powerfull of source control 🧰😉 near your hands

# [author of posts]
author: davorpa

# ["true" or "false" to indicate whether to provide a download URL]
show_downloads: false

# [Your Google Analytics tracking ID]
google_analytics: UA-203788397-3

# [Number of posts in one paginated section (default: 3)]
paginate: 5

# Declare rubygem used plugins
plugins:
  - jekyll-remote-theme
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

# Include/Exclude some files from site deployment
include:
  - README.md
  - LICENSE.md
  - COPYING.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
exclude:
  - "LICENSE"
  - "**.xcf"

gist:
  # Disabling noscript support. Default: true
  # By default, Jekyll Gist will make an HTTP call per Gist to retrieve the raw content of the Gist. This information is used to propagate noscript tags for search engines and browsers without JavaScript support. If you'd like to disable this feature, for example, to speed up builds locally, add the following to your site's _config.yml:
  noscript: true
